FROM grafana/grafana:4.3.2

RUN apt-get update && \
    apt-get install -y curl gettext-base && \
    rm -rf /var/lib/apt/lists/*

COPY ./grafana.ini /etc/grafana/grafana.ini
COPY ./dashboards /etc/grafana/dashboards
COPY ./datasources /etc/grafana/datasources

COPY ./entrypoint.sh .
RUN chmod +x entrypoint.sh

RUN rm -rf /var/lib/grafana/.init

ENTRYPOINT ["./entrypoint.sh"]